server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: cambio-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: sgs
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  flyway:
    enabled: true
    url: jdbc:mysql://127.0.0.1:3306/cambio_service
    schemas: cambio_service
    user: sgs
    locations: classpath:db/migration
    baseline-on-migrate: true
  management:
    tracing:
      sampling:
        probability: 1.0
    zipkin:
      tracing:
        endpoint: http://localhost:9411/api/v2/spans
springdoc:
  show-actuator: true
  api-docs:
    enabled: true
    path: /cambio-service/v3/api-docs
#  swagger-ui:
#    path: /cambio-service/swagger-ui.html
#    urls:
#      - name: cambio-service
#        url: /cambio-service/v3/api-docs
