server:
  port: 8000

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: cambio-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cambio_service?useTimezone=true&serverTimezone=UTC
    username: sgs
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

  flyway:
    enabled: true
    url: jdbc:mysql://127.0.0.1:3306/cambio_service
    schemas: cambio_service
    user: sgs
    locations: classpath:db/migration
    baseline-on-migrate: true

#    config:
#      import: optional:configserver:http://localhost:8888/
#      cloud:
#        config:
#          profile: prod
#    management:
#      endpoints:
#        web:
#          exposure:
#            include: "*"